version: "3.9"

services:
  oracle:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: oracle
    command: ["node", "oracle.js"]
    ports:
      - "3001:3001"
    restart: always

  indexer:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: indexer
    command: ["node", "indexer.js"]
    ports:
      - "3002:3002"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - oracle
      - indexer
    environment:
      VITE_ORACLE_BASE_URL: "http://localhost:3001"
      VITE_INDEXER_BASE_URL: "http://localhost:3002"
    restart: always
